server:
  port: 8082

spring:
  application:
    name: spring-mini

datasource:
  spring-mini:
    jdbc-url: jdbc:mysql://localhost:3306/${spring.application.name}
    username: deepblue
    password: deepblue123456

point-cut:
  match: "do*"

