server:
  port: 8080

spring:
  application:
    name: spring-mini

datasource:
  spring-mini:
    jdbc-url: jdbc:mysql://localhost:3306/deepblue
    username: deepblue
    password: deepblue123456


